services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - app-network
    environment:
      - MONGODB_PASSWORD=adminpass
      - SECRET_KEY=MYSECRET

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
