# Use node 17 alpine image
FROM node:17-alpine


RUN rm -rf /root/.npm

# Clear npm cache and install dependencies including nodemon
RUN npm cache clean --force && npm install -g nodemon

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Start the application using nodemon
CMD ["npm", "start"]
